### ISSUE TITLE
初始化集群失败

### ISSUE THREAD

**Issue by nicefuture2016** [boilingfrog/ansible-mongo-replicaset-role#1]
TASK [mongo : 初始化副本集] ****************************************************************************************************************************************************
skipping: [192.168.100.182]
skipping: [192.168.100.183]
[WARNING]: The value ******** (type int) in a string field was converted to u'********' (type string). If this does not look like what you expect, quote the entire value
to ensure it does not change.
fatal: [192.168.100.181]: FAILED! => {"changed": false, "msg": "Unable to authenticate with MongoDB: check_compatibility() takes exactly 2 arguments (3 given)"}

TASK [启动 mongo] **********************************************************************************************************************************************************
changed: [192.168.100.182]
changed: [192.168.100.183]

PLAY RECAP ***************************************************************************************************************************************************************
192.168.100.181            : ok=27   changed=6    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
192.168.100.182            : ok=25   changed=7    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0   
192.168.100.183            : ok=25   changed=7    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0

**Comment by boilingfrog** [comment]
192.168.100.181是干净的吗

**Comment by nicefuture2016** [comment]
> 192.168.100.181是干净的吗

新装的系统
系统版本是：CentOS Linux release 7.9.2009 (Core)
ansible版本：ansible 2.9.16
pymongo (3.7.1)
python2.7

**Comment by nicefuture2016** [comment]
> 192.168.100.181是干净的吗

留个联系方式吗？

**Comment by boilingfrog** [comment]
微信：16638021163

nicefuture2016 <notifications@github.com> 于2021年1月15日周五 上午10:23写道：

**Comment by boilingfrog** [comment]
微信：Lz_boilingFrog

**Comment by zhituanchen** [comment]
您好：
  请问一下这个怎么解决的呢，我这边也遇到这种情况 @nicefuture2016 @boilingfrog 

task path: /root/soft/ansible-mongo-replicaset-role/roles/mongo/tasks/init_replicaset.yml:7
ok: [192.168.8.102] => (item=192.168.8.102) => {"ansible_facts": {"replicaset_host": ["192.168.8.102:27017"]}, "ansible_loop_var": "item", "changed": false, "item": "192.168.8.102"}
ok: [192.168.8.102] => (item=192.168.8.103) => {"ansible_facts": {"replicaset_host": ["192.168.8.102:27017", "192.168.8.103:27017"]}, "ansible_loop_var": "item", "changed": false, "item": "192.168.8.103"}
skipping: [192.168.8.103] => (item=192.168.8.102)  => {"ansible_loop_var": "item", "changed": false, "item": "192.168.8.102", "skip_reason": "Conditional result was False"}
skipping: [192.168.8.103] => (item=192.168.8.103)  => {"ansible_loop_var": "item", "changed": false, "item": "192.168.8.103", "skip_reason": "Conditional result was False"}

TASK [mongo : 注册replicaset_host变量] *********************************************************************************************************************************************************************************
task path: /root/soft/ansible-mongo-replicaset-role/roles/mongo/tasks/init_replicaset.yml:12
skipping: [192.168.8.103] => {"changed": false, "skip_reason": "Conditional result was False"}
 [WARNING]: The value ******** (type int) in a string field was converted to u'********' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.

fatal: [192.168.8.102]: FAILED! => {"changed": false, "msg": "MongoDB Replicaset validation failed. Invalid number of replicaset members."}

**Comment by boilingfrog** [comment]
没记错的话，mongo的副本集，最少需要三个节点。
