### ISSUE TITLE
RROR! no action detected in task.

### ISSUE THREAD

**Issue by zhituanchen** [boilingfrog/ansible-mongo-replicaset-role#2]
您好：
   执行时候报错，请问怎么处理呢
[root@cluster1 ansible-mongo-replicaset-role]#       ansible-playbook deploy-mongo.yml  

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/soft/ansible-mongo-replicaset-role/roles/mongo/tasks/init_replicaset.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: 初始化副本集
  ^ here

The error appears to have been in '/root/soft/ansible-mongo-replicaset-role/roles/mongo/tasks/init_replicaset.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: 初始化副本集
  ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/soft/ansible-mongo-replicaset-role/roles/mongo/tasks/init_replicaset.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: 初始化副本集
  ^ here

**Comment by boilingfrog** [comment]
ansibles是那个版本呢，ansible的版本需要在2.8之上。

**Comment by zhituanchen** [comment]
好的，我这边修改从ansible 2.4.0.0升级到ansible 2.8.9，运行没有这个错误了，感谢回复。
